resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 2 * * *"
  displayName: Daily at 2AM
  branches:
    include:
    - master

variables:
- name: projectName
  value: 'templ-test46'

- group: ados-group-names-templ-test01
- group: ados-acls-templ-test01
- group: ados-git-params-templ-test01
- group: ados-secrets

parameters:
- name: checkArtifactFeed
  displayName: 'Check Artifact Feed?'
  type: boolean
  default: false

jobs:
- job: check_project
  displayName: 'Check project'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7.x'
    inputs:
      versionSpec: 3.7.x

  - bash: |
      pip install --disable-pip-version-check --ignore-installed --quiet --user --requirement requirements.txt
    displayName: 'Install requirements'


  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_project_info.py
      arguments: '--organization kagarlickij --projectName $(projectName) --pat $(cloud_pat)'
    displayName: 'Export project-related info'


  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-administrators group info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(developers-group-name) --groupSid $(developers-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-developers group info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-auditors group info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-product-owners group info'


  - template: ./templates/check-groups.yml
  - template: ./templates/check-project-permissions.yml
  - template: ./templates/check-analytics-permissions.yml
  - template: ./templates/check-library-permissions.yml
  - template: ./templates/check-git.yml
  - template: ./templates/check-build-permissions.yml
  - template: ./templates/check-release-permissions.yml

  - ${{ if eq(parameters.checkArtifactFeed, true) }}:
    - task: PythonScript@0
      inputs:
        scriptPath: ./common/export_feed_info.py
        arguments: '--organization https://feeds.dev.azure.com/kagarlickij --feedName $(projectName) --pat $(cloud_pat)'
      displayName: 'Export feed-related info'
    - template: ./templates/check-feed-permissions.yml
