resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 2 * * *"
  displayName: Daily at 2AM
  branches:
    include:
    - master

variables:
- name: projectName
  value: 'templ-test43'

- group: ados-group-names-templ-test01
- group: ados-acls-templ-test01
- group: ados-git-params-templ-test01
- group: ados-secrets

jobs:
- job: create_project
  displayName: 'Check project'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7.x'
    inputs:
      versionSpec: 3.7.x

  - bash: |
      pip install --disable-pip-version-check --ignore-installed --quiet --user --requirement requirements.txt
    displayName: 'Install requirements'


  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_project_info.py
      arguments: '--organization kagarlickij --projectName $(projectName) --pat $(cloud_pat)'
    displayName: 'Export project-related info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/get_groups.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --desiredGroupsList $(administrators-group-name) $(developers-group-name) $(auditors-group-name) $(product-owners-group-name) "$(projectName) Team" "Project Administrators" "Project Valid Users" --pat $(cloud_pat)'
    displayName: 'Check list of groups'


  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/get_group_members.py
      arguments: '--organization kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName "Project Administrators" --desiredMembersQuantity 1 --pat $(cloud_pat)'
    displayName: 'Check Project Administrators group members'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/get_group_members.py
      arguments: '--organization kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName "Project Valid Users" --desiredMembersQuantity 0 --pat $(cloud_pat)'
    displayName: 'Check Project Valid Users group members'


  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-administrators group info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(developers-group-name) --groupSid $(developers-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-developers group info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-auditors group info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_group_info.py
      arguments: '--organization https://vssps.dev.azure.com/kagarlickij --projectScopeDescriptor $(projectScopeDescriptor) --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --pat $(cloud_pat)'
    displayName: 'Export $(projectName)-product-owners group info'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 52d39943-cb85-4d7f-8fa8-c6baac873819 --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-project-allow-permissions) --deny $(administrators-project-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Project permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 52d39943-cb85-4d7f-8fa8-c6baac873819 --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-project-allow-permissions) --deny $(developers-project-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Project permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 52d39943-cb85-4d7f-8fa8-c6baac873819 --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-project-allow-permissions) --deny $(auditors-project-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Project permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 52d39943-cb85-4d7f-8fa8-c6baac873819 --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-project-allow-permissions) --deny $(product-owners-project-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Project permissions for $(projectName)-product-owners group'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId d34d3680-dfe5-4cc6-a949-7d9c68f73cba --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-analytics-allow-permissions) --deny $(administrators-analytics-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Analytics permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId d34d3680-dfe5-4cc6-a949-7d9c68f73cba --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-analytics-allow-permissions) --deny $(developers-analytics-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Analytics permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId d34d3680-dfe5-4cc6-a949-7d9c68f73cba --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-analytics-allow-permissions) --deny $(auditors-analytics-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Analytics permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId d34d3680-dfe5-4cc6-a949-7d9c68f73cba --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-analytics-allow-permissions) --deny $(product-owners-analytics-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Analytics permissions for $(projectName)-product-owners group'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId b7e84409-6553-448a-bbb2-af228e07cbeb --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-library-allow-permissions) --deny $(administrators-library-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Library permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId b7e84409-6553-448a-bbb2-af228e07cbeb --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-library-allow-permissions) --deny $(developers-library-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Library permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId b7e84409-6553-448a-bbb2-af228e07cbeb --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-library-allow-permissions) --deny $(auditors-library-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Library permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId b7e84409-6553-448a-bbb2-af228e07cbeb --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-library-allow-permissions) --deny $(product-owners-library-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Library permissions for $(projectName)-product-owners group'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/check_git_repos.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectName $(projectName) --maxCommitAge $(maxCommitAge) --maxPullRequestAge $(maxPullRequestAge) --minApproverCount $(minApproverCount) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Git repos settings'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87 --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-git-allow-permissions) --deny $(administrators-git-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Git permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87 --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-git-allow-permissions) --deny $(developers-git-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Git permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87 --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-git-allow-permissions) --deny $(auditors-git-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Git permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87 --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-git-allow-permissions) --deny $(product-owners-git-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Git permissions for $(projectName)-product-owners group'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 33344d9c-fc72-4d6f-aba5-fa317101a7e9 --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-build-allow-permissions) --deny $(administrators-build-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Build permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 33344d9c-fc72-4d6f-aba5-fa317101a7e9 --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-build-allow-permissions) --deny $(developers-build-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Build permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 33344d9c-fc72-4d6f-aba5-fa317101a7e9 --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-build-allow-permissions) --deny $(auditors-build-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Build permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId 33344d9c-fc72-4d6f-aba5-fa317101a7e9 --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-build-allow-permissions) --deny $(product-owners-build-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Build permissions for $(projectName)-product-owners group'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId c788c23e-1b46-4162-8f5e-d7585343b5de --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-release-allow-permissions) --deny $(administrators-release-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Release permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId c788c23e-1b46-4162-8f5e-d7585343b5de --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-release-allow-permissions) --deny $(developers-release-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Release permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId c788c23e-1b46-4162-8f5e-d7585343b5de --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-release-allow-permissions) --deny $(auditors-release-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Release permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_permissions.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectId $(projectId) --namespaceId c788c23e-1b46-4162-8f5e-d7585343b5de --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-release-allow-permissions) --deny $(product-owners-release-deny-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Release permissions for $(projectName)-product-owners group'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/export_feed_info.py
      arguments: '--organization https://feeds.dev.azure.com/kagarlickij --feedName $(projectName) --pat $(cloud_pat)'
    displayName: 'Export feed-related info'


  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_feed_acl.py
      arguments: '--organization https://feeds.dev.azure.com/kagarlickij --projectName $(projectName) --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --feedId $(feedId) --role $(administrators-feed-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Feed permissions for $(projectName)-administrators group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_feed_acl.py
      arguments: '--organization https://feeds.dev.azure.com/kagarlickij --projectName $(projectName) --groupName $(developers-group-name) --groupSid $(developers-group-sid) --feedId $(feedId) --role $(developers-feed-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Feed permissions for $(projectName)-developers group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_feed_acl.py
      arguments: '--organization https://feeds.dev.azure.com/kagarlickij --projectName $(projectName) --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --feedId $(feedId) --role $(auditors-feed-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Feed permissions for $(projectName)-auditors group'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/get_feed_acl.py
      arguments: '--organization https://feeds.dev.azure.com/kagarlickij --projectName $(projectName) --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --feedId $(feedId) --role $(product-owners-feed-permissions) --pat $(cloud_pat)'
    continueOnError: true
    displayName: 'Check Feed permissions for $(projectName)-product-owners group'
