- repo: local
  hooks:
    - id: black
      name: Code format with Black
      entry: black
      args:
        - .
      language: system
      types:
        - python
      stages:
        - commit
    - id: bandit
      name: Security check with Bandit
      entry: bandit
      args:
        - '--recursive'
        - '-ll'
        - .
      language: system
      types:
        - python
      stages:
        - push
