resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: false
  branches:
    exclude:
    - '*'

variables:
- name: gistId
  value: '780fabe68201e08c8f2151ad02898bad'
- group: github-secrets

jobs:
- job: build
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  pool:
    name: Default
  steps:
  - powershell: |
      $env:Path += ";C:\Users\Administrator\AppData\Roaming\Python\Python38\Scripts"
      pip install --disable-pip-version-check --ignore-installed --quiet --user --requirement requirements.txt
    displayName: 'Install Python requirements'
  - powershell: |
      $env:Path += ";C:\Users\Administrator\AppData\Roaming\Python\Python38\Scripts"
      pip install --disable-pip-version-check --ignore-installed --quiet --version pylint==2.5.0
      pip install --disable-pip-version-check --ignore-installed --quiet anybadge==1.7.0
    displayName: 'Install pylint and anybadge'
  # - powershell: |
  #     python ./common/generate_pylint_badge.py --gistId $(gistId) --gitHubPat $(gitHubPat)
  #   displayName: 'Generate pylint badge' #TODO: https://stackoverflow.com/questions/62488844/run-pylint-against-all-files-in-windows
