resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 2 * * *"
  displayName: Daily at 2AM
  branches:
    include:
    - master

variables:
- name: projectName
  value: 'templ-test06'

- group: ados-group-names-templ-test01
- group: ados-acls-templ-test01
- group: ados-git-params-templ-test01
- group: ados-secrets

jobs:
- job: create_project
  displayName: 'Check project'
  pool:
    name: Default
  steps:

  - powershell: |
      $env:Path += ";C:\Users\Administrator\AppData\Roaming\Python\Python38\Scripts"
      pip install --user -r requirements.txt
    displayName: 'Install requirements'
    continueOnError: true


  - powershell: |
      python ./onprem/export_project_info.py --projectName $(projectName) --pat $(onprem_pat)
    displayName: 'Export project-related info'


  - powershell: |
      sleep 1
      ./onprem/get_groups.ps1 -ORGANIZATION 'https://ados.demo.kagarlickij.com/DefaultCollection' -PROJECT_ID $Env:PROJECT_ID
    displayName: 'Get list of all groups'
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./onprem/get_groups.py --desiredGroupsList '$(administrators-group-name)' '$(developers-group-name)' '$(auditors-group-name)' '$(product-owners-group-name)' '$(projectName) Team' 'Build Administrators' 'Contributors' 'Project Administrators' 'Project Valid Users' 'Readers' 'Release Administrators'
    displayName: 'Check list of groups'


  - powershell: |
      sleep 1
      python ./onprem/export_group_info.py --groupName $(administrators-group-name) --groupAce $(administrators-group-ace)
    displayName: 'Export $(projectName)-administrators group info'

  - powershell: |
      sleep 1
      python ./onprem/export_group_info.py --groupName $(developers-group-name) --groupAce $(developers-group-ace)
    displayName: 'Export $(projectName)-developers group info'

  - powershell: |
      sleep 1
      python ./onprem/export_group_info.py --groupName $(auditors-group-name) --groupAce $(auditors-group-ace)
    displayName: 'Export $(projectName)-auditors group info'

  - powershell: |
      sleep 1
      python ./onprem/export_group_info.py --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace)
    displayName: 'Export $(projectName)-product-owners group info'


  - powershell: |
      sleep 1
      ./onprem/get_group_members.ps1 -ORGANIZATION 'https://ados.demo.kagarlickij.com/DefaultCollection' -PROJECT_NAME $(projectName) -GROUP_NAME 'Build Administrators'
    displayName: 'Get Build Administrators group members'

  - powershell: |
      sleep 1
      python ./onprem/get_group_members.py --groupName 'Build Administrators' --desiredMembersQuantity '0'
    displayName: 'Check Build Administrators group members'

  - powershell: |
      sleep 1
      ./onprem/get_group_members.ps1 -ORGANIZATION 'https://ados.demo.kagarlickij.com/DefaultCollection' -PROJECT_NAME $(projectName) -GROUP_NAME 'Contributors'
    displayName: 'Get Contributors group members'

  - powershell: |
      sleep 1
      python ./onprem/get_group_members.py --groupName 'Contributors' --desiredMembersQuantity '2'
    displayName: 'Check Contributors group members'

  - powershell: |
      sleep 1
      ./onprem/get_group_members.ps1 -ORGANIZATION 'https://ados.demo.kagarlickij.com/DefaultCollection' -PROJECT_NAME $(projectName) -GROUP_NAME 'Project Administrators'
    displayName: 'Get Project Administrators group members'

  - powershell: |
      sleep 1
      python ./onprem/get_group_members.py --groupName 'Project Administrators' --desiredMembersQuantity '1'
    displayName: 'Check Project Administrators group members'

  - powershell: |
      sleep 1
      ./onprem/get_group_members.ps1 -ORGANIZATION 'https://ados.demo.kagarlickij.com/DefaultCollection' -PROJECT_NAME $(projectName) -GROUP_NAME 'Project Valid Users'
    displayName: 'Get Project Valid Users group members'

  - powershell: |
      sleep 1
      python ./onprem/get_group_members.py --groupName 'Project Valid Users' --desiredMembersQuantity '11'
    displayName: 'Check Project Valid Users group members'

  - powershell: |
      sleep 1
      ./onprem/get_group_members.ps1 -ORGANIZATION 'https://ados.demo.kagarlickij.com/DefaultCollection' -PROJECT_NAME $(projectName) -GROUP_NAME 'Readers'
    displayName: 'Get Readers group members'

  - powershell: |
      sleep 1
      python ./onprem/get_group_members.py --groupName 'Readers' --desiredMembersQuantity '0'
    displayName: 'Check Readers group members'


  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(administrators-group-name) --groupAce $(administrators-group-ace) --allow $(administrators-project-allow-permissions) --deny $(administrators-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(developers-group-name) --groupAce $(developers-group-ace) --allow $(developers-project-allow-permissions) --deny $(developers-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(auditors-group-name) --groupAce $(auditors-group-ace) --allow $(auditors-project-allow-permissions) --deny $(auditors-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace) --allow $(product-owners-project-allow-permissions) --deny $(product-owners-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(administrators-group-name) --groupAce $(administrators-group-ace) --allow $(administrators-analytics-allow-permissions) --deny $(administrators-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(developers-group-name) --groupAce $(developers-group-ace) --allow $(developers-analytics-allow-permissions) --deny $(developers-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(auditors-group-name) --groupAce $(auditors-group-ace) --allow $(auditors-analytics-allow-permissions) --deny $(auditors-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace) --allow $(product-owners-analytics-allow-permissions) --deny $(product-owners-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(administrators-group-name) --groupAce $(administrators-group-ace) --allow $(administrators-git-allow-permissions) --deny $(administrators-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(developers-group-name) --groupAce $(developers-group-ace) --allow $(developers-git-allow-permissions) --deny $(developers-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(auditors-group-name) --groupAce $(auditors-group-ace) --allow $(auditors-git-allow-permissions) --deny $(auditors-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace) --allow $(product-owners-git-allow-permissions) --deny $(product-owners-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      sleep 1
      python ./common/check_git_repos.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectName $(projectName) --maxCommitAge $(maxCommitAge) --maxPullRequestAge $(maxPullRequestAge) --minApproverCount $(minApproverCount) --pat $(onprem_pat)
    displayName: 'Check Git repos settings'
    continueOnError: true


  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(administrators-group-name) --groupAce $(administrators-group-ace) --allow $(administrators-build-allow-permissions) --deny $(administrators-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(developers-group-name) --groupAce $(developers-group-ace) --allow $(developers-build-allow-permissions) --deny $(developers-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(auditors-group-name) --groupAce $(auditors-group-ace) --allow $(auditors-build-allow-permissions) --deny $(auditors-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace) --allow $(product-owners-build-allow-permissions) --deny $(product-owners-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(administrators-group-name) --groupAce $(administrators-group-ace) --allow $(administrators-release-allow-permissions) --deny $(administrators-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(developers-group-name) --groupAce $(developers-group-ace) --allow $(developers-release-allow-permissions) --deny $(developers-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(auditors-group-name) --groupAce $(auditors-group-ace) --allow $(auditors-release-allow-permissions) --deny $(auditors-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      sleep 1
      python ./common/get_ace.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace) --allow $(product-owners-release-allow-permissions) --deny $(product-owners-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./onprem/export_feed_info.py --feedName $(projectName) --pat $(onprem_pat)
    displayName: 'Export feed-related info'


  - powershell: |
      sleep 1
      python ./onprem/get_feed_acl.py --groupName $(administrators-group-name) --groupAce $(administrators-group-ace) --feedId $Env:FEED_ID --role $(administrators-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)

  - powershell: |
      sleep 1
      python ./onprem/get_feed_acl.py --groupName $(developers-group-name) --groupAce $(developers-group-ace) --feedId $Env:FEED_ID --role $(developers-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)

  - powershell: |
      sleep 1
      python ./onprem/get_feed_acl.py --groupName $(auditors-group-name) --groupAce $(auditors-group-ace) --feedId $Env:FEED_ID --role $(auditors-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)

  - powershell: |
      sleep 1
      python ./onprem/get_feed_acl.py --groupName $(product-owners-group-name) --groupAce $(product-owners-group-ace) --feedId $Env:FEED_ID --role $(product-owners-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)
