resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 2 * * *"
  displayName: Daily at 2AM
  branches:
    include:
    - master

variables:
- name: projectName
  value: 'templ-test25'

- group: ados-group-names-templ-test01
- group: ados-acls-templ-test01
- group: ados-git-params-templ-test01
- group: ados-secrets

jobs:
- job: create_project
  displayName: 'Check project'
  pool:
    name: Default
  steps:

  - powershell: |
      $env:Path += ";C:\Users\Administrator\AppData\Roaming\Python\Python38\Scripts"
      pip install --disable-pip-version-check --ignore-installed --quiet --user --requirement requirements.txt
    displayName: 'Install requirements'
    continueOnError: true


  - powershell: |
      python ./onprem/export_project_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectName $(projectName) --pat $(onprem_pat)
    displayName: 'Export project-related info'


  - powershell: |
      python ./onprem/get_groups.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $(projectId) --desiredGroupsList '$(administrators-group-name)' '$(developers-group-name)' '$(auditors-group-name)' '$(product-owners-group-name)' '$(projectName) Team' 'Project Administrators' 'Project Valid Users'
    displayName: 'Check list of groups'
    continueOnError: true


  - powershell: |
      python ./onprem/export_group_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $(projectId) --groupName $(administrators-group-name) --groupSid $(administrators-group-sid)
    displayName: 'Export $(projectName)-administrators group info'

  - powershell: |
      python ./onprem/export_group_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $(projectId) --groupName $(developers-group-name) --groupSid $(developers-group-sid)
    displayName: 'Export $(projectName)-developers group info'

  - powershell: |
      python ./onprem/export_group_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $(projectId) --groupName $(auditors-group-name) --groupSid $(auditors-group-sid)
    displayName: 'Export $(projectName)-auditors group info'

  - powershell: |
      python ./onprem/export_group_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $(projectId) --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid)
    displayName: 'Export $(projectName)-product-owners group info'


  - powershell: |
      python ./onprem/get_group_members.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectName $(projectName) --groupName 'Project Administrators' --desiredMembersQuantity '1'
    displayName: 'Check Project Administrators group members'
    continueOnError: true

  - powershell: |
      python ./onprem/get_group_members.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectName $(projectName) --groupName 'Project Valid Users' --desiredMembersQuantity '7'
    displayName: 'Check Project Valid Users group members'
    continueOnError: true


  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-project-allow-permissions) --deny $(administrators-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-project-allow-permissions) --deny $(developers-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-project-allow-permissions) --deny $(auditors-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '52d39943-cb85-4d7f-8fa8-c6baac873819' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-project-allow-permissions) --deny $(product-owners-project-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Project permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-analytics-allow-permissions) --deny $(administrators-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-analytics-allow-permissions) --deny $(developers-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-analytics-allow-permissions) --deny $(auditors-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'd34d3680-dfe5-4cc6-a949-7d9c68f73cba' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-analytics-allow-permissions) --deny $(product-owners-analytics-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Analytics permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'b7e84409-6553-448a-bbb2-af228e07cbeb' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-library-allow-permissions) --deny $(administrators-library-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Library permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'b7e84409-6553-448a-bbb2-af228e07cbeb' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-library-allow-permissions) --deny $(developers-library-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Library permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'b7e84409-6553-448a-bbb2-af228e07cbeb' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-library-allow-permissions) --deny $(auditors-library-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Library permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'b7e84409-6553-448a-bbb2-af228e07cbeb' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-library-allow-permissions) --deny $(product-owners-library-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Library permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./common/check_git_policy.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectName $(projectName) --maxCommitAge $(maxCommitAge) --maxPullRequestAge $(maxPullRequestAge) --minApproverCount $(minApproverCount) --pat $(onprem_pat)
    displayName: 'Check Git repos settings'
    continueOnError: true


  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-git-allow-permissions) --deny $(administrators-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-git-allow-permissions) --deny $(developers-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-git-allow-permissions) --deny $(auditors-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-git-allow-permissions) --deny $(product-owners-git-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Git permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-build-allow-permissions) --deny $(administrators-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-build-allow-permissions) --deny $(developers-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-build-allow-permissions) --deny $(auditors-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId '33344d9c-fc72-4d6f-aba5-fa317101a7e9' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-build-allow-permissions) --deny $(product-owners-build-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Build permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --allow $(administrators-release-allow-permissions) --deny $(administrators-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --allow $(developers-release-allow-permissions) --deny $(developers-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --allow $(auditors-release-allow-permissions) --deny $(auditors-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)

  - powershell: |
      python ./common/check_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectId $Env:PROJECT_ID --namespaceId 'c788c23e-1b46-4162-8f5e-d7585343b5de' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --allow $(product-owners-release-allow-permissions) --deny $(product-owners-release-deny-permissions) --pat $(onprem_pat)
    displayName: 'Check Release permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      PROJECT_ID: $(projectId)


  - powershell: |
      python ./common/export_feed_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --feedName $(projectName) --pat $(onprem_pat)
    displayName: 'Export feed-related info'


  - powershell: |
      python ./common/check_feed_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --groupName $(administrators-group-name) --groupSid $(administrators-group-sid) --feedId $Env:FEED_ID --role $(administrators-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-administrators group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)

  - powershell: |
      python ./common/check_feed_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --groupName $(developers-group-name) --groupSid $(developers-group-sid) --feedId $Env:FEED_ID --role $(developers-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-developers group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)

  - powershell: |
      python ./common/check_feed_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --groupName $(auditors-group-name) --groupSid $(auditors-group-sid) --feedId $Env:FEED_ID --role $(auditors-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-auditors group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)

  - powershell: |
      python ./common/check_feed_permissions.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --groupName $(product-owners-group-name) --groupSid $(product-owners-group-sid) --feedId $Env:FEED_ID --role $(product-owners-feed-permissions) --pat $(onprem_pat)
    displayName: 'Check Feed permissions for $(projectName)-product-owners group'
    continueOnError: true
    env:
      FEED_ID: $(feedId)
