resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 2 * * *"
  displayName: Daily at 2AM
  branches:
    include:
    - master

variables:
- name: projectName
  value: 'templ-test50'
- name: createArtifactFeed
  value: true
- group: ados-group-names-templ-test01
- group: ados-acls-templ-test01
- group: ados-git-params-templ-test01
- group: ados-secrets

jobs:
- job: create_project
  displayName: 'Check project'
  pool:
    name: Default
  steps:

  - powershell: |
      $env:Path += ";C:\Users\Administrator\AppData\Roaming\Python\Python38\Scripts"
      pip install --disable-pip-version-check --ignore-installed --quiet --user --requirement requirements.txt
    displayName: 'Install requirements'
    continueOnError: true

  - powershell: |
      python ./onprem/export_project_info.py --organization 'https://ados.demo.kagarlickij.com/DefaultCollection' --projectName $(projectName) --pat $(onprem_pat)
    displayName: 'Export project-related info'

  - template: ./templates/export-groups-info.yml
  - template: ./templates/check-groups.yml
  - template: ./templates/check-project-permissions.yml
  - template: ./templates/check-analytics-permissions.yml
  - template: ./templates/check-library-permissions.yml
  - template: ./templates/check-git.yml
  - template: ./templates/check-build-permissions.yml
  - template: ./templates/check-release-permissions.yml
  - template: ./templates/check-feed-permissions.yml
